### ISSUE TITLE
Publish an "/odom" message using a "nav_msgs/Odometry"

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#345]
It is necessary to publish information about Odometry on ROS.
http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html

Tasks:

* [x] Analysis of ROSJava NXT Node
* [x] Develop Publisher for ROSBridge
* [ ] Execute tests

**LeJOS Forum request:**
https://lejos.sourceforge.io/forum/viewtopic.php?f=18&t=8867

**Dev Notes:**
In the future, it is necessary to add support for GyroAdapter:
http://www.lejos.org/ev3/docs/lejos/robotics/GyroscopeAdapter.html

**Examples:**
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos/nxt_lejos_proxy/src/org/lejos/ros/sensors/OdometrySensor.java
https://github.com/dsapandora/SIMUL_DSA/blob/master/rosjava/rosjava_tutorial_pubsub/src/main/java/org/ros/rosjava_tutorial_pubsub/RobotMover.java
https://github.com/heuristicus/int-robot/blob/master/trunk/src/main/java/util/OdomUtil.java
https://github.com/xylifyx/lejos/blob/master/ros/nxt_lejos/nxt_lejos_proxy/src/org/lejos/ros/nodes/ROSProxy.java
http://wiki.ros.org/navigation/Tutorials/RobotSetup/Odom
https://github.com/elmot/ev3javabrick/blob/master/ros-ev3-node/src/main/java/elmot/ros/ev3/OdoComputer.java
https://github.com/srmanikandasriram/ev3-ros/blob/master/src/teleop_odom.cpp

**Comment by jabrena** [comment]
https://github.com/linorobot/linorobot/wiki/3.-Odometry

**Comment by jabrena** [comment]
https://github.com/KTH-RAS/ras_arduino_inos/blob/indigo-2015/closedloop/closedloop.ino

**Comment by jabrena** [comment]
https://github.com/julianangel/EmotionBot/blob/master/TriskarTre/TriskarTre-0-1/TriskarTre-0-1.ino

**Comment by jabrena** [comment]
https://github.com/ecostech/rosproxy/blob/master/rosproxy_arduino/sketchbook/Odom.ino

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos_ros/lcp_proxy/src/org/lejos/ros/nxt/navigation/DifferentialNavigationSystem.java

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos/nxt_lejos_proxy/src/org/lejos/ros/sensors/OdometrySensor.java

**Comment by jabrena** [comment]
```  
header: 
  seq: 36
  stamp: 
    secs: 1505759241
    nsecs: 687000064
  frame_id: base_link
child_frame_id: base_footprint
pose: 
  pose: 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 1.0
      y: 0.0
      z: 0.0
      w: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist: 
  twist: 
    linear: 
      x: 0.0
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
