### ISSUE TITLE
Publish the topic "/range" using a "sensor_msgs/Range"

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#347]
It is necessary to add support for a RangeFinder on EV3.

Currently, exist 2 alternatives on EV3 to use a RangeFinder:

* EV3 IR Sensor
* EV3 Ultrasonic Sensor

Tasks:

* [x] Develop node for EV3IRSensor
* [x] Develop node for EV3UltrasonicSensor
* [x] Execute tests for IRSensor
* [x] Execute tests for Ultrasonic Sensor
* [ ] Review EV3 Sensor units vs ROS Range Units

**Examples:**
The following examples could be useful to publish a Range message on ROS using both sensors.
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos/nxt_lejos_proxy/src/org/lejos/ros/sensors/
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos/nxt_lejos_proxy/src/org/lejos/ros/sensors/UltrasonicSensor.java
https://github.com/Hacks4ROS/h4r_ev3_ctrl/blob/develop/h4r_ev3_control/src/h4r_ev3_control/ev3_ultrasonic_controller.cpp
https://github.com/Hacks4ROS/h4r_ev3_ctrl/blob/develop/h4r_ev3_control/src/h4r_ev3_control/ev3_infrared_controller.cpp
https://github.com/srmanikandasriram/ev3-ros/blob/master/src/ultrasonic_sensor.cpp
https://github.com/NCharabaruk/maxsonar_arduino_ros/blob/master/maxsonar_arduino_ros.ino

**Comment by jabrena** [comment]
Implemented both sensors.
Pending tests.

**Comment by jabrena** [comment]
Related issue:
https://github.com/rctoris/jrosbridge/issues/24

**Comment by jabrena** [comment]
Initial tests with a IR Sensor:

``` 
header: 
  seq: 428
  stamp: 
    secs: 1505425774
    nsecs:  51000064
  frame_id: base_link
radiation_type: 1
field_of_view: 0.0500000007451
min_range: 0.0500000007451
max_range: 0.800000011921
range: 43.0
```

**Comment by jabrena** [comment]
Initial tests with a US Sensor:

``` 
header: 
  seq: 264
  stamp: 
    secs: 1505426295
    nsecs: 107000064
  frame_id: base_link
radiation_type: 0
field_of_view: 0.0500000007451
min_range: 0.0500000007451
max_range: 2.5
range: 73.5
```
