### ISSUE TITLE
Publish a "/tf" message using a "tf/tfMessage"

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/ev3dev-lang-java#367]
http://docs.ros.org/api/tf/html/msg/tfMessage.html

http://turtlebot3.robotis.com/en/latest/bringup.html
http://wiki.ros.org/navigation/Tutorials/RobotSetup
http://wiki.ros.org/tf
http://wiki.ros.org/tf/Tutorials/Introduction%20to%20tf
https://github.com/linorobot/linorobot/wiki/5.-TF
http://wiki.ros.org/navigation/Tutorials/RobotSetup/TF

https://github.com/mintar/rosjava_tf_example/blob/master/src/main/java/rosjava_tf_example/Transformer.java

**Comment by jabrena** [comment]
http://wiki.ros.org/navigation/Tutorials/RobotSetup/Sensors
http://library.isr.ist.utl.pt/docs/roswiki/laser_pipeline(2f)Tutorials(2f)IntroductionToWorkingWithLaserScannerData.html

**Comment by jabrena** [comment]
http://docs.ros.org/jade/api/geometry_msgs/html/msg/Transform.html

**Comment by jabrena** [comment]
https://github.com/robopeak/rplidar_ros/blob/master/launch/test_rplidar.launch

``` 
<launch>
  <node name="rplidarNode"          pkg="rplidar_ros"  type="rplidarNode" output="screen">
  <param name="serial_port"         type="string" value="/dev/ttyUSB0"/>  
  <param name="serial_baudrate"     type="int"    value="115200"/>
  <param name="frame_id"            type="string" value="laser"/>
  <param name="inverted"            type="bool"   value="false"/>
  <param name="angle_compensate"    type="bool"   value="true"/>
 
 </node>
  <node name="rplidarNodeClient"          pkg="rplidar_ros"  type="rplidarNodeClient" output="screen">
  </node>
</launch>
```

**Comment by jabrena** [comment]
https://github.com/robopeak/rplidar_ros/blob/master/launch/view_rplidar.launch

**Comment by jabrena** [comment]
https://github.com/robopeak/rplidar_ros/blob/master/rviz/rplidar.rviz

**Comment by jabrena** [comment]
http://www.hessmer.org/blog/2011/04/10/2d-slam-with-ros-and-kinect/

**Comment by jabrena** [comment]
http://www.hessmer.org/blog/2012/02/11/ardros-transform-between-base_link-and-the-kinect-sensor/

**Comment by jabrena** [comment]
[ WARN] [1505126193.824068698]: MessageFilter [target=map ]: Dropped 100.00% of messages so far. Please turn the [ros.rviz.message_notifier] rosconsole logger to DEBUG for more information.

```
rosrun tf static_transform_publisher 0 0 0 0 0 0 "base" "base_scan" 100
roswtf
```

**Comment by jabrena** [comment]
https://sourceforge.net/p/lejos/nxt/code/HEAD/tree/trunk/ros/nxt_lejos_ros/lcp_proxy/src/org/lejos/ros/nxt/navigation/DifferentialNavigationSystem.java

**Comment by jabrena** [comment]
http://docs.ros.org/api/tf/html/msg/tfMessage.html

**Comment by jabrena** [comment]
Used on gmapping.
http://wiki.ros.org/gmapping#Required_tf_Transforms

**Comment by jabrena** [comment]
``` 
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1505759090
        nsecs: 404999936
      frame_id: base_link
    child_frame_id: base_footprint
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 1.0
        y: 0.0
        z: 0.0
        w: 0.0
```
